#!/bin/bash

#SBATCH --output=logs/slurm-%x_%j_model_%A_%a.out
#SBATCH --gpus=1
#SBATCH --mem-per-cpu=4096
#SBATCH --time=05:00:00
#SBATCH --signal=USR1@60
#SBATCH --array=0-2 


module purge
module load stack/.2024-06-silent gcc/12.2.0 python_cuda/3.11.6

# Define the list of models
models=("Baseline" "RNN" "MultiRNN")

# Select the model corresponding to this array task index
model="${models[$SLURM_ARRAY_TASK_ID]}"

# Run the Python script with the specified model argument
srun python3 -u realignment/maxinter.py --model "$model"
