#!/bin/bash

#SBATCH --output=logs/slurm-%x_%j.out
#SBATCH --cpus-per-task=5
#SBATCH --gpus=1
#SBATCH --mem-per-cpu=1024
#SBATCH --time=00:45:00
#SBATCH --signal=USR1@60


module purge
module load stack/.2024-06-silent  gcc/12.2.0 python_cuda/3.11.6

srun python3 -u CUB_maxinter.py
